# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

# Set variables once
variables:
  configuration: info
  platform: x64
  vmImage: 'ubuntu-latest'

trigger:
- trigger

pool:
  vmImage: $(vmImage)

steps:
- script: echo "Hello123" 
